name = "nibble"
version = "0.3.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["MIT"]
description = "A string parsing library heavily inspired by elm/parser."
repository = { type = "github", user = "hayleigh-dot-dev", repo = "gleam-nibble" }
gleam = ">= 0.34.0"

[dependencies]
gleam_stdlib = "~> 0.34"

[dev-dependencies]
gleeunit = "~> 1.0"
